---
title: "Online Books"
author: "SW"
date: Last updated on `r Sys.Date()`
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Applied Statistics

* [Applied Statistics with Python Volume I: Introductory Statistics and Regression](https://stevenkhwun.github.io/Test/Books/Applied_Statistics/Kaganovskiy_Applied-Statistics-with-Python.pdf), PDF version, by _Leon Kaganovskiy_. (1st Edition, 2025)

* [Applied Univariate, Bivariate, and Multivariate Statistics Using Python](https://stevenkhwun.github.io/Test/Books/Applied_Statistics/Denis_Applied-Statistics-Using-Python.pdf), PDF version, by _Daniel J. Denis_. (2021)

* [Applied Univariate, Bivariate, and Multivariate Statistics: Understanding Statistics for Social and Natural Scientists, with Applications in SPSS and R](https://stevenkhwun.github.io/Test/Books/Applied_Statistics/Denis_Applied-Statistics-with-Applications-in-SPSS-and-R.pdf), PDF version, by _Daniel J. Denis_. (2nd Edition, 2021)


* [Modern Statistics with R: From wrangling and exploring data to inference and predictive modelling](https://www.modernstatisticswithr.com/), Web Version, by _Måns Thulin_. (2nd Edition, March 2025)


## Machine Learning


* [An Introduction to Statistical Learning with Applications in Python](https://stevenkhwun.github.io/Test/Books/Machine_Learning/ISLP_website-compressed.pdf), PDF version, by _Gareth James, Daniela Witten, Trevor Hastie, Robert Tibshirani and Jonathan Taylor_. Printed on 5 July 2023.

  
## Mathematics

* [Solving Mathematical Problems: A Personal Perspective](https://stevenkhwun.github.io/Test/Books/Mathematics/solving-mathematical-problems-terence-tao.pdf), PDF version, by _Terence Tao_. (2nd Edition, 2006)

  Personal website of the author can be found at https://terrytao.wordpress.com/.




## Python

* [Python for Data Analysis: Data Wrangling with pandas, NumPy, and Jupyter](https://wesmckinney.com/book/), Web version, by _Wes McKinney_. (3rd Edition, September 2022)

* [Python for Excel: A Modern Environment for Automation and Data Analysis](https://stevenkhwun.github.io/Test/Books/Python/Python-for-Excel.pdf), PDF version, by _Felix Zumstein_. (1st Edition, March 2021)
  
  The GitHub site of the book can be found [here](https://github.com/fzumstein/python-for-excel).
  

## R

* [R for Data Science: Import, Tidy, Transform, Visualize, and Model Data](https://r4ds.hadley.nz/), Web version, by _Hadley Wickham, Mine Cetinkaya-Rundel, and Garrett Grolemund_. (2nd Edition, July 2023)

  * The solutions to the exercises of the book can be found [here](https://mine-cetinkaya-rundel.github.io/r4ds-solutions/). 
<br>
<br>
* [Modern Data Science with R](https://mdsr-book.github.io/mdsr3e/), Web version, by _Benjamin S. Baumer, Daniel T. Kaplan, and Nicholas J. Horton_. (3rd Edition (in progress), July 2024)<br>
  * The 2nd edition of the book can be found [here](https://mdsr-book.github.io/mdsr2e/).